apiVersion: apps/v1
kind: Deployment
metadata:
  name: superapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: superapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: superapp
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
