apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: Pod
metadata:
  namespace: development
  name: myapp
  labels:
    name: myapp
    teams: developers
spec:
  containers:
  - name: myapp
    image: nginx:latest
    ports:
    - containerPort: 80