apiVersion: v1
kind: Pod
metadata:
  name: sudopod
  labels:
    team: DevOps
    class: a-data
    stage: production
    type: AB
spec:
  containers:
    - name: wordpress
      image: worddspress
      resources:
        limits:
            memory: "256Mi"
            cpu: "500m"
      ports:
        - containerPort: 80