apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  restartPolicy: Never
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 20']
