apiVersion: v1
kind: Pod
metadata:
  name: sudo
  labels:
    team: DevOps
    class: a-data
    stage: production
    type: AB
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu
      image: alpine:latest      
      command: ['sh', '-c', 'echo "sfdd" && sleep 10']
      